const productsEl=document.querySelector('#storeProducts')||document.querySelector('#products'),searchEl=document.querySelector('#search'),categoryEl=document.querySelector('#category'),drawer=document.querySelector('#cartDrawer');
const CART_KEY='electroshop_new_store_cart_v2',RATE_KEY='electroshop_usd_ils_rate';let catalogReady=false,catalogFailed=false,products=[],cart=readSharedCart(),language=localStorage.getItem('electroshop_store_language')||'he',usdRate=Number(localStorage.getItem(RATE_KEY))||null,promotionEnabled=false;
function readSharedCart(){try{const value=JSON.parse(localStorage.getItem('electroshop_new_store_cart_v2')||'{}');return value&&typeof value==='object'&&!Array.isArray(value)?value:{}}catch{return {}}}
import('./shop-api.js').then(api=>api.getProducts()).then(remote=>{
  products=remote.map(mergeProductSizes);catalogReady=true;document.dispatchEvent(new CustomEvent('electroshop-catalog-ready',{detail:remote}));
  // Preserve baskets created in the earlier preview when the real catalog starts.
  const preview=ElectroshopCatalog.get(),migrated={};
  for(const [key,item] of Object.entries(cart)){
    const old=preview.find(p=>p.id===item.productId),current=old&&products.find(p=>p.sku===old.sku);
    const id=current?.id||item.productId,newKey=current?key.replace(item.productId,id):key;
    migrated[newKey]={...item,productId:id};
  }
  cart=migrated;localStorage.setItem(CART_KEY,JSON.stringify(cart));renderProducts();renderCart();
}).catch(()=>{catalogReady=true;catalogFailed=true;renderProducts();renderCart()});
window.addEventListener('storage',event=>{if(event.key===CART_KEY){cart=readSharedCart();renderCart()}});
window.addEventListener('pageshow',()=>{cart=readSharedCart();renderCart()});
import('./shop-api.js?v=7').then(api=>api.getPromotionSettings()).then(settings=>{promotionEnabled=settings.enabled;renderCart()}).catch(()=>{promotionEnabled=false;renderCart()});
const languageButton=document.querySelector('#langToggle');
document.querySelector('#checkout').addEventListener('click',e=>{e.stopImmediatePropagation();location.href='shop-checkout.html'},true);
const text={he:{shop:'כל מה שצריך באלקטרושופ',sub:'החנות החדשה של Electroshop - סביבת בדיקה פרטית',search:'חיפוש מוצר',all:'כל הקטגוריות',necklaces:'שרשראות',rings:'טבעות',bracelets:'צמידים',color:'צבע',size:'מידה',style:'אפשרות',choose:'נא לבחור',add:'הוספה לעגלה',empty:'מוצרים יתווספו בקרוב',cart:'סל הקניות',remove:'הסרה',total:'סה״כ',emptyCart:'הסל עדיין ריק',checkout:"המשך לצ'ק אאוט",notice:'מצב בדיקה - לא מתבצע חיוב',continueShopping:'חזרה לחנות',lang:'English'},en:{shop:'Find your next upgrade',sub:'The new Electroshop store - private test environment',search:'Search products',all:'All categories',necklaces:'Necklaces',rings:'Rings',bracelets:'Bracelets',color:'Color',size:'Size',style:'Option',choose:'Please choose',add:'Add to cart',empty:'No products found',cart:'Shopping cart',remove:'Remove',total:'Estimated total',emptyCart:'Your cart is empty',checkout:'Continue to checkout',notice:'USD prices are for display. The final charge will be processed in ILS.',continueShopping:'Continue Shopping',lang:'עברית'}};
const t=key=>text[language][key];
const usdAmount=(amount,product)=>{const ils=Number(amount),manual=Number(product?.priceUsd),isSalePrice=Number(product?.price)===ils;if(isSalePrice&&manual>0)return Math.round(manual);if(!Number.isFinite(ils)||ils<=0)return null;return Math.max(1,Math.round(ils/3.7))};
const usdPrice=p=>usdAmount(p.price,p);
const money=(amount,product)=>{if(language==='he')return `${Number(amount).toLocaleString('he-IL')} ש״ח`;const usd=usdAmount(amount,product);return usd!==null?`$${usd.toFixed(2)}`:'$--'};
const optionTranslations={'זהב':'Gold','צבע זהב':'Gold','מוזהב':'Gold','כסף':'Silver','כסוף':'Silver','צבע כסף':'Silver','מוכסף':'Silver','רוז גולד':'Rose Gold','זהב ורוד':'Rose Gold','שחור':'Black','לבן':'White','כחול':'Blue','אדום':'Red','ירוק':'Green','קצר':'Short','קצרה':'Short','ארוך':'Long','ארוכה':'Long','קטן':'Small','קטנה':'Small','בינוני':'Medium','בינונית':'Medium','גדול':'Large','גדולה':'Large','מתכוונן':'Adjustable','מתכווננת':'Adjustable','נשים':'Women','גברים':'Men'};
const optionText=value=>{const raw=String(value).trim();if(language!=='en')return raw;return optionTranslations[raw]||raw.replace(/מילימטרים/g,'millimeters').replace(/מילימטר/g,'millimeter').replace(/ס\s*["״']?\s*מ/g,'cm').replace(/מ\s*["״']?\s*מ/g,'mm').replace(/קצרה|קצר/g,'Short').replace(/ארוכה|ארוך/g,'Long').replace(/קטנה|קטן/g,'Small').replace(/בינונית|בינוני/g,'Medium').replace(/גדולה|גדול/g,'Large').replace(/מתכווננת|מתכוונן/g,'Adjustable')};
const escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const variantSelect=(label,name,values)=>values?.length?`<label><select name="${name}" required aria-label="${escapeHtml(label)}"><option value="" selected>${escapeHtml(label)}</option>${values.map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(optionText(v))}</option>`).join('')}</select></label>`:'';
const combinedSizeOptions=product=>{const sizes=(product.sizes||[]).filter(Boolean),styles=(product.styles||[]).filter(Boolean);if(!styles.length)return sizes;if(!sizes.length)return styles;if(styles.length===1)return sizes.map(size=>`${size} - ${styles[0]}`);if(styles.length===sizes.length)return sizes.map((size,index)=>`${size} - ${styles[index]}`);return sizes.flatMap(size=>styles.map(style=>`${size} - ${style}`))};
function mergeProductSizes(product){return {...product,sizes:combinedSizeOptions(product),styles:[]}}
products=products.map(mergeProductSizes);
const imageForColor=(product,color)=>{const index=(product.imageColors||[]).findIndex(value=>value===color);return index>=0?product.images[index]:product.images[0]};
const promotionBox=document.createElement('div');promotionBox.id='cartPromotion';promotionBox.className='cart-promotion';document.querySelector('#cartLines').after(promotionBox);
const promotionFor=prices=>{const count=prices.length,cheapest=count?Math.min(...prices):0,rate=count>=5?1:count>=4?.5:0;return {count,rate,discount:promotionEnabled?cheapest*rate:0}};
const promotionMessage=promo=>language==='he'?(promo.rate===1?'המבצע הופעל: המוצר החמישי במתנה - הזול מביניהם! 🎁':promo.rate===.5?'המבצע הופעל: המוצר הרביעי ב 50% הנחה - הזול מביניהם! 🎉':'בקניית 3 פריטים קבל את המוצר הרביעי ב 50% הנחה - הזול מביניהם. בקניית 4 פריטים קבל את החמישי במתנה - הזול מביניהם!'):(promo.rate===1?'Offer applied: the fifth item is free - the cheapest item! 🎁':promo.rate===.5?'Offer applied: the fourth item is 50% off - the cheapest item! 🎉':'Buy 3 items and get the fourth at 50% off - the cheapest item. Buy 4 items and get the fifth free - the cheapest item!');
const selectedVariant=(product,choice={})=>(product.variants||[]).find(variant=>{const sizeLabel=[variant.size,variant.style].filter(Boolean).join(' - ');return (!variant.color||variant.color===choice.color)&&(!sizeLabel||sizeLabel===choice.size)});
const deviceChoiceValid=(p,c)=>!p.sku?.startsWith('PELEPHONE-')||!!(p.variants||[]).find(v=>v.color===(c.color||'')&&v.size===(c.size||'')&&v.available===true);
const selectedPrice=(product,choice)=>{const value=selectedVariant(product,choice)?.price;return value!==null&&value!==''&&Number.isFinite(Number(value))?Number(value):product.price};
const cleanDescription=value=>{const template=document.createElement('template');template.innerHTML=String(value||'').replace(/\n/g,'<br>');template.content.querySelectorAll('*').forEach(node=>{if(!['BR','B','STRONG','I','EM','U','UL','OL','LI','A','P','DIV'].includes(node.tagName)){node.replaceWith(...node.childNodes);return}[...node.attributes].forEach(attribute=>{if(!(node.tagName==='A'&&attribute.name==='href'))node.removeAttribute(attribute.name)});if(node.tagName==='A'&&!/^https?:\/\//i.test(node.getAttribute('href')||''))node.removeAttribute('href')});return template.innerHTML};
async function loadRate(){try{const response=await fetch('https://www.boi.org.il/PublicApi/GetExchangeRates?');const data=await response.json(),usd=data.exchangeRates?.find(x=>x.key==='USD')?.currentExchangeRate;if(usd){usdRate=Number(usd);localStorage.setItem(RATE_KEY,String(usdRate));if(language==='en'){renderProducts();renderCart()}}}catch{}}
function applyLanguage(){document.documentElement.lang=language;document.documentElement.dir=language==='he'?'rtl':'ltr';searchEl.placeholder=t('search');categoryEl.options[0].text=t('all');document.querySelector('.drawer-head h2').textContent=t('cart');document.querySelector('#checkout').textContent=t('checkout');document.querySelector('.notice').textContent=t('notice');renderProducts();renderCart()}
function saveCart(){localStorage.setItem(CART_KEY,JSON.stringify(cart));renderCart()}

function refreshDeviceChoice(root,p,detail=false){
 if(!p?.sku?.startsWith('PELEPHONE-'))return;
 const selects=[...root.querySelectorAll('.variant-fields select')],choice=Object.fromEntries(selects.map(s=>[s.name,s.value]));
 for(const select of selects)for(const option of select.options){if(!option.value)continue;option.disabled=!(p.variants||[]).some(v=>v.available===true&&v[select.name]===option.value&&selects.every(other=>other===select||!other.value||v[other.name]===other.value));}
 const valid=deviceChoiceValid(p,choice),button=root.querySelector(detail?'.product-detail-add':'.button.add'),price=root.querySelector(detail?'.product-detail-price':'.price');
 if(button){button.dataset.variantInvalid=String(!valid);button.disabled=!valid;}
 const matching=(p.variants||[]).filter(v=>v.available===true&&(!choice.color||v.color===choice.color)&&(!choice.size||v.size===choice.size));
 const prices=matching.map(v=>Number(v.price)).filter(value=>Number.isFinite(value)&&value>0);
 if(price){const min=prices.length?Math.min(...prices):null,max=prices.length?Math.max(...prices):null;price.textContent=min===null?(language==='he'?'השילוב אינו זמין':'Combination unavailable'):(min===max?'':(language==='he'?'החל מ־':'From '))+money(min,p);}
}

const deviceBrand=p=>{const name=p.nameEn||p.nameHe||'';return /iphone|apple/i.test(name)?'Apple':/samsung/i.test(name)?'Samsung':/xiaomi|redmi|poco/i.test(name)?'Xiaomi':/nokia/i.test(name)?'Nokia':/vivo/i.test(name)?'Vivo':/normande/i.test(name)?'Normande':/future/i.test(name)?'Future':'Other'};
const deviceModelOrder=new Intl.Collator('en',{numeric:true,sensitivity:'base'});
const sortDevices=(a,b)=>{const brands=['Apple','Samsung','Xiaomi','Nokia','Vivo','Normande','Future','Other'],brandA=deviceBrand(a),brandB=deviceBrand(b),group=brands.indexOf(brandA)-brands.indexOf(brandB);if(group)return group;const series=p=>{const name=p.nameEn||'';if(brandA==='Samsung')return /Galaxy S/i.test(name)?0:/Galaxy Z Fold/i.test(name)?1:/Galaxy Z Flip/i.test(name)?2:3;if(brandA==='Xiaomi')return /Redmi Note/i.test(name)?1:/Redmi/i.test(name)?2:/Poco/i.test(name)?3:0;return 0};return series(a)-series(b)||deviceModelOrder.compare(b.nameEn||b.nameHe,a.nameEn||a.nameHe)||String(a.sku).localeCompare(String(b.sku))};
function renderProducts(){const q=searchEl.value.trim().toLowerCase(),cat=categoryEl.value;const pageCategory=document.querySelector('main[data-store-category]')?.dataset.storeCategory||document.querySelector('[data-category]')?.dataset.category;const list=products.filter(p=>!(productsEl.dataset.excludeSkus||'').split(',').includes(p.sku)&&(!pageCategory||p.category===pageCategory)&&(!productsEl.dataset.featured||p.featured)&&p.active&&(!cat||p.category===cat)&&(!q||p.nameHe.toLowerCase().includes(q)||p.nameEn.toLowerCase().includes(q)||p.sku.toLowerCase().includes(q)));if(pageCategory==='smartphones')list.sort(sortDevices);productsEl.innerHTML=list.length?list.map(p=>`<article class="product" data-product="${p.id}"><div class="product-image-wrap"><img src="${p.images[0]}" alt="${language==='he'?p.nameHe:p.nameEn}" loading="lazy"><span class="product-info-badge" aria-hidden="true">i</span></div><div class="product-body"><h2>${language==='he'?p.nameHe:p.nameEn}</h2>${p.category==='car-mounts'&&p.sku==='ELECTRO-005'?`<a class="button secondary" href="shop-carholder.html">${language==='he'?'פרטים':'Details'}</a>`:''}<div class="variant-fields">${variantSelect(t('color'),'color',p.colors)}${variantSelect(p.sku?.startsWith('PELEPHONE-')?(language==='he'?'נפח אחסון':'Storage'):t('size'),'size',p.sizes)}</div><div class="price-row">${p.regularPrice>p.price?`<span class="old">${money(p.regularPrice,p)}</span>`:''}<span class="price">${money(p.price,p)}</span></div><button class="button add" data-id="${p.id}">${t('add')}</button></div></article>`).join(''):`<div class="empty">${!catalogReady?(language==='he'?'טוען מוצרים...':'Loading products...'):catalogFailed?(language==='he'?'לא ניתן לטעון מוצרים כרגע. נסו לרענן את הדף.':'Products could not load. Please refresh.') :t('empty')}</div>`;productsEl.querySelectorAll('[data-product]').forEach(card=>refreshDeviceChoice(card,products.find(p=>p.id===card.dataset.product)))}
function renderCart(){
  let invalidDevice=false;for(const item of Object.values(cart)){const p=products.find(p=>p.id===item.productId);if(p?.sku?.startsWith('PELEPHONE-')){if(deviceChoiceValid(p,item))item.price=selectedPrice(p,item);else invalidDevice=true}}

  const validItems=Object.entries(cart).map(([key,item])=>({key,item,product:products.find(product=>product.id===item.productId)})).filter(line=>line.product);
  document.querySelector('#cartLines').innerHTML=validItems.map(({key,item,product})=>{const safeKey=escapeHtml(key),choices=[item.color,item.size,item.style].filter(Boolean).map(optionText).join(' | '),price=Number(item.price??product.price);return `<div class="cart-line"><img src="${item.image||product.images[0]}" alt=""><div><strong>${language==='he'?product.nameHe:product.nameEn}</strong>${choices?`<small><br>${choices}</small>`:''}<div>${money(price,product)}</div><div class="qty"><button data-action="minus" data-key="${safeKey}">−</button><span>${item.qty}</span><button data-action="plus" data-key="${safeKey}">+</button></div></div><button class="remove" data-action="remove" data-key="${safeKey}">${t('remove')}</button></div>`}).join('')||`<div class="empty">${t('emptyCart')}</div>`;
  const pricesIls=[],pricesUsd=[];for(const {item,product} of validItems){const ils=Number(item.price??product.price),usd=usdAmount(ils,product)||0;for(let i=0;i<item.qty;i++){pricesIls.push(ils);pricesUsd.push(usd)}}
  const promoIls=promotionFor(pricesIls),promoUsd=promotionFor(pricesUsd),subtotalIls=pricesIls.reduce((sum,price)=>sum+price,0),subtotalUsd=pricesUsd.reduce((sum,price)=>sum+price,0),shippingIls=validItems.some(({product,item})=>item.qty>0&&(product.category==='smartphones'||product.sku?.startsWith('PELEPHONE-')))?50:0,totalIls=subtotalIls-promoIls.discount+shippingIls,totalUsd=subtotalUsd-promoUsd.discount+(shippingIls?usdAmount(shippingIls):0),count=pricesIls.length;
  promotionBox.hidden=!promotionEnabled;promotionBox.innerHTML=promotionEnabled?`<strong>${promotionMessage(language==='he'?promoIls:promoUsd)}</strong>${promoIls.discount?`<span>${language==='he'?`חסכת ${promoIls.discount.toLocaleString('he-IL')} ש״ח`:`You saved $${promoUsd.discount.toFixed(2)}`}</span>`:''}`:'';
  document.querySelector('#cartCount').textContent=count;document.querySelector('#cartTotal').innerHTML=(promotionEnabled&&promoIls.discount?`<small>${language==='he'?'סכום לפני הנחה':'Subtotal'}: ${language==='he'?`${subtotalIls.toLocaleString('he-IL')} ש״ח`:`$${subtotalUsd.toFixed(2)}`}</small><small class="discount">${language==='he'?'הנחת מבצע':'Offer discount'}: −${language==='he'?`${promoIls.discount.toLocaleString('he-IL')} ש״ח`:`$${promoUsd.discount.toFixed(2)}`}</small>`:'')+(shippingIls?`<small>${language==='he'?'משלוח מכשירים':'Device shipping'}: ${money(shippingIls)}</small>`:'')+`<span>${t('total')}</span><span>${language==='he'?`${totalIls.toLocaleString('he-IL')} ש״ח`:`$${totalUsd.toFixed(2)}`}</span>`;document.querySelector('#checkout').disabled=!count||invalidDevice;if(invalidDevice)document.querySelector('#cartTotal').innerHTML='<small>'+ (language==='he'?'אפשרות מכשיר בעגלה אינה זמינה. הסירו אותה ובחרו מחדש.':'A device option is unavailable. Remove it and choose again.')+'</small>'
}
const detailModal=document.createElement('div');detailModal.className='product-detail-modal';detailModal.innerHTML='<div class="product-detail-card" role="dialog" aria-modal="true"><button class="product-detail-close" aria-label="סגירה">×</button><div class="product-detail-gallery"><img class="product-detail-main" alt=""><div class="product-detail-thumbs"></div><div class="product-detail-video-wrap"><video class="product-detail-video" controls playsinline muted preload="metadata"></video><button class="product-detail-video-preview" type="button" aria-label="הפעלת הווידאו"><img alt=""><span aria-hidden="true">▶</span></button></div></div><div class="product-detail-copy"><h2></h2><div class="product-detail-price"></div><p></p><div class="product-detail-options variant-fields"></div><button class="button product-detail-add" type="button"></button></div></div>';document.body.append(detailModal);
let productDetailScrollY=0;
function openProduct(p,choice={}){if(p.category==='car-mounts'&&p.sku==='ELECTRO-005'){location.href='shop-carholder.html';return;}const images=p.images?.filter(Boolean)||[],main=detailModal.querySelector('.product-detail-main'),thumbs=detailModal.querySelector('.product-detail-thumbs'),video=detailModal.querySelector('.product-detail-video'),videoWrap=detailModal.querySelector('.product-detail-video-wrap'),videoPreview=detailModal.querySelector('.product-detail-video-preview'),previewImage=videoPreview.querySelector('img');main.src=images[0]||'';main.alt=language==='he'?p.nameHe:p.nameEn;thumbs.innerHTML=images.map((src,i)=>`<button class="${i===0?'active':''}" data-detail-image="${i}"><img src="${src}" alt=""></button>`).join('');const productNumber=String(p.sku||'').match(/(\d+)$/)?.[1],videoSrc=p.videos?.[0]||'';video.pause();video.muted=true;video.defaultMuted=true;video.poster=images[0]||'';previewImage.src=images[0]||'';videoPreview.hidden=false;videoWrap.style.display=videoSrc?'block':'none';if(videoSrc){video.src=videoSrc;video.load()}else{video.removeAttribute('src');video.removeAttribute('poster')}video.onerror=()=>{videoWrap.style.display='none';video.removeAttribute('src')};detailModal.querySelector('h2').textContent=language==='he'?p.nameHe:p.nameEn;detailModal.querySelector('.product-detail-price').textContent=money(p.price,p);detailModal.querySelector('p').innerHTML=cleanDescription(language==='he'?(p.descriptionHe||''):(p.descriptionEn||''));detailModal.querySelector('.product-detail-options').innerHTML=variantSelect(t('color'),'color',p.colors)+variantSelect(p.sku?.startsWith('PELEPHONE-')?(language==='he'?'נפח אחסון':'Storage'):t('size'),'size',p.sizes);detailModal.querySelector('.product-detail-add').textContent=t('add');detailModal.dataset.product=p.id;for(const select of detailModal.querySelectorAll('.product-detail-options select'))if(choice[select.name])select.value=choice[select.name];if(choice.color)main.src=imageForColor(p,choice.color);productDetailScrollY=window.scrollY;document.body.style.top=`-${productDetailScrollY}px`;document.body.classList.add('product-detail-open');detailModal.classList.add('open');refreshDeviceChoice(detailModal,p,true);detailModal.querySelector('.product-detail-card').scrollTop=0;detailModal.querySelector('.product-detail-close').focus()}
function closeProductDetail(){detailModal.querySelector('.product-detail-video').pause();detailModal.classList.remove('open');document.body.classList.remove('product-detail-open');document.body.style.top='';window.scrollTo(0,productDetailScrollY)}
detailModal.addEventListener('click',e=>{const preview=e.target.closest('.product-detail-video-preview');if(preview){const video=detailModal.querySelector('.product-detail-video');preview.hidden=true;video.muted=true;video.play().catch(()=>{preview.hidden=false});return}const add=e.target.closest('.product-detail-add');if(add){const p=products.find(x=>x.id===detailModal.dataset.product),selects=[...detailModal.querySelectorAll('.product-detail-options select')];if(selects.some(s=>!s.value)){selects.find(s=>!s.value).focus();return}const choice=Object.fromEntries(selects.map(s=>[s.name,s.value])),key=[p.id,choice.color,choice.size,choice.style].filter(Boolean).join('::');if(!deviceChoiceValid(p,choice)){alert(language==='he'?'שילוב הצבע והנפח אינו זמין כרגע. בחרו אפשרות אחרת.':'This colour and storage combination is unavailable.');return}cart[key]??={productId:p.id,qty:0,...choice,price:selectedPrice(p,choice),image:imageForColor(p,choice.color)};cart[key].price=selectedPrice(p,choice);cart[key].qty+=1;saveCart();closeProductDetail();drawer.classList.add('open');return}const thumb=e.target.closest('[data-detail-image]');if(thumb){detailModal.querySelector('.product-detail-main').src=thumb.querySelector('img').src;detailModal.querySelectorAll('[data-detail-image]').forEach(x=>x.classList.toggle('active',x===thumb));return}if(e.target===detailModal||e.target.closest('.product-detail-close'))closeProductDetail()});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&detailModal.classList.contains('open'))closeProductDetail()});
productsEl.addEventListener('click',e=>{const b=e.target.closest('.add');if(!b){if(e.target.closest('select,a'))return;const card=e.target.closest('[data-product]');if(card)openProduct(products.find(x=>x.id===card.dataset.product),Object.fromEntries([...card.querySelectorAll('.variant-fields select')].map(select=>[select.name,select.value])));return}const card=b.closest('[data-product]'),p=products.find(x=>x.id===b.dataset.id),selects=[...card.querySelectorAll('select')];if(selects.some(s=>!s.value)){selects.find(s=>!s.value).focus();return}const choice=Object.fromEntries(selects.map(s=>[s.name,s.value])),key=[p.id,choice.color,choice.size,choice.style].filter(Boolean).join('::');if(!deviceChoiceValid(p,choice)){alert(language==='he'?'שילוב הצבע והנפח אינו זמין כרגע. בחרו אפשרות אחרת.':'This colour and storage combination is unavailable.');return}cart[key]??={productId:p.id,qty:0,...choice,price:selectedPrice(p,choice),image:imageForColor(p,choice.color)};cart[key].price=selectedPrice(p,choice);cart[key].qty+=1;saveCart();drawer.classList.add('open')});
document.querySelector('#cartLines').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const {key,action}=b.dataset,item=cart[key];if(action==='plus')item.qty+=1;if(action==='minus')item.qty=Math.max(item.qty-1,0);if(action==='remove'||item.qty===0)delete cart[key];saveCart()});
productsEl.addEventListener('change',event=>{const select=event.target.closest('.variant-fields select');if(!select)return;const card=select.closest('[data-product]'),product=products.find(item=>item.id===card?.dataset.product),choice=Object.fromEntries([...card.querySelectorAll('.variant-fields select')].map(item=>[item.name,item.value])),image=card?.querySelector('.product-image-wrap>img');if(product&&image&&select.name==='color')image.src=imageForColor(product,select.value);if(product)card.querySelector('.price').textContent=money(selectedPrice(product,choice),product);refreshDeviceChoice(card,product)});
detailModal.addEventListener('change',event=>{const select=event.target.closest('.product-detail-options select');if(!select)return;const product=products.find(item=>item.id===detailModal.dataset.product),choice=Object.fromEntries([...detailModal.querySelectorAll('.product-detail-options select')].map(item=>[item.name,item.value])),src=product&&imageForColor(product,choice.color);if(src&&select.name==='color'){detailModal.querySelector('.product-detail-main').src=src;detailModal.querySelectorAll('[data-detail-image]').forEach(button=>button.classList.toggle('active',button.querySelector('img').src===new URL(src,location.href).href))}if(product)detailModal.querySelector('.product-detail-price').textContent=money(selectedPrice(product,choice),product);refreshDeviceChoice(detailModal,product,true)});
document.addEventListener('electroshop-language-change',event=>{language=event.detail;localStorage.setItem('electroshop_store_language',language);applyLanguage()});searchEl.addEventListener('input',renderProducts);categoryEl.addEventListener('change',()=>{if(categoryEl.value&&document.querySelector('[data-category]')){location.href='shop-'+categoryEl.value+'.html'}else renderProducts()});document.querySelector('#cartButton').onclick=()=>drawer.classList.add('open');document.querySelector('#closeCart').onclick=()=>drawer.classList.remove('open');document.querySelector('#checkout').onclick=()=>alert(language==='he'?'העגלה והסכום מוכנים. חיבור התשלום יופעל לאחר העברת מסוף טרנזילה.':'The cart and total are ready. Payment will be enabled after the Tranzila terminal is transferred.');applyLanguage();loadRate();
const modelLightbox=document.createElement('div');modelLightbox.className='model-lightbox';modelLightbox.setAttribute('aria-hidden','true');modelLightbox.innerHTML='<button class="model-lightbox-close" type="button" aria-label="סגירת תמונה">×</button><img alt="">';document.body.append(modelLightbox);document.querySelector('#modelGallery')?.addEventListener('click',event=>{const image=event.target.closest('.model-gallery img');if(!image)return;modelLightbox.querySelector('img').src=image.src;modelLightbox.classList.add('open');modelLightbox.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'});modelLightbox.addEventListener('click',event=>{if(event.target===modelLightbox||event.target.closest('.model-lightbox-close')){modelLightbox.classList.remove('open');modelLightbox.setAttribute('aria-hidden','true');modelLightbox.querySelector('img').removeAttribute('src');document.body.style.overflow=''}});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&modelLightbox.classList.contains('open'))modelLightbox.querySelector('.model-lightbox-close').click()});

document.addEventListener('electroshop-open-sku',event=>{const p=products.find(p=>p.sku===event.detail&&p.active);if(p)openProduct(p)});
