import {createOrderSaver,moveVisibleProduct,placeVisibleProduct} from './shop-product-order.js?v=drag-1';
import('./shop-api.js?v=option-images-2').then(async api=>{
  const session=await api.getSession();if(!session){location.replace('shop-login.html');return}try{if(!await api.isAdmin(session)){api.signOut();location.replace('shop-login.html');return}}catch{location.replace('shop-login.html');return}
  let products=await api.getProducts(session),primaryImage='',additionalImages=[],imageColors=[],productVideos=[],currentVariants=[];const list=document.querySelector('#list'),modal=document.querySelector('#modal'),form=document.querySelector('#form'),statusEl=document.querySelector('#status'),formStatusEl=document.querySelector('#formStatus'),primaryPreview=document.querySelector('#primaryImagePreview'),additionalPreview=document.querySelector('#additionalImagesPreview'),variantsList=document.querySelector('#variantsList');
  const pageParams=new URLSearchParams(location.search),editorId=pageParams.get('edit'),editorMode=location.pathname.endsWith('/shop-product-editor.html')||pageParams.has('new')||!!editorId;let contextCategory=pageParams.get('category')||'';form.elements.category.dataset.contextCategory=contextCategory;const editorUrl=id=>`shop-product-editor.html?${id?`edit=${encodeURIComponent(id)}`:'new=1'}${!id&&contextCategory?'&category='+encodeURIComponent(contextCategory):''}`;if(editorMode)document.body.classList.add('product-editor-page');
  const videoField=document.createElement('label');videoField.className='field full upload-field';videoField.innerHTML='<span>סרטון מוצר</span><input id="productVideoFiles" type="file" accept="video/mp4,video/webm,video/quicktime"><small>אפשר להעלות MP4, WebM או MOV. מומלץ סרטון קצר ודחוס.</small>';const videoPreview=document.createElement('div');videoPreview.id='productVideosPreview';videoPreview.className='video-preview field full';additionalPreview.after(videoField,videoPreview);
  const logout=document.createElement('button');logout.className='button danger';logout.textContent='יציאה';logout.onclick=()=>{api.signOut();location.replace('shop-login.html')};document.querySelector('.head-actions').append(logout);
  const ordersLink=document.createElement('a');ordersLink.className='button secondary';ordersLink.href='shop-orders.html';ordersLink.target='_blank';ordersLink.rel='noopener';ordersLink.textContent='ניהול הזמנות';document.querySelector('.head-actions').prepend(ordersLink);
  const importDescriptions=document.createElement('button');importDescriptions.type='button';
  const usdField=document.createElement('label');usdField.className='field';usdField.innerHTML='<span>מחיר בדולרים - אופציונלי</span><input name="priceUsd" type="number" min="0" step="0.01" placeholder="יחושב אוטומטית אם יישאר ריק"><small>ניתן לקבוע מחיר ידני או להשאיר ריק להמרה אוטומטית</small>';form.elements.price.closest('label').after(usdField);
  function status(message,type='ok'){const target=modal.classList.contains('open')?formStatusEl:statusEl;target.textContent=message;target.className=`status show ${type}${target===formStatusEl?' form-status':''}`;clearTimeout(target.hideTimer);target.hideTimer=setTimeout(()=>target.className=`status${target===formStatusEl?' form-status':''}`,4000)}
  const filterBar=document.createElement('div');filterBar.className='admin-category-filter';
  filterBar.innerHTML='<label for="adminCategoryFilter">הצגת מוצרים לפי קטגוריה</label><select id="adminCategoryFilter"><option value="">כל הקטגוריות</option></select><label for="adminProductSearch">חיפוש מוצר</label><input id="adminProductSearch" type="search" placeholder="שם מוצר או מק״ט" autocomplete="off"><span role="status"></span>';
  list.before(filterBar);const categoryFilter=filterBar.querySelector('select');
  let categoryRows=[];try{categoryRows=await api.request('/rest/v1/electroshop_categories?select=slug,name_he,aliases&order=sort_order.asc',{token:session.accessToken})}catch{}
  contextCategory=categoryRows.find(c=>c.slug===contextCategory||(c.aliases||[]).includes(contextCategory))?.slug||contextCategory;
  const categoryNames=new Map(categoryRows.map(c=>[c.slug,c.name_he]));
  for(const slug of new Set([...categoryNames.keys(),...products.flatMap(p=>p.categories||[p.category]),contextCategory].filter(Boolean)))categoryFilter.add(new Option(categoryNames.get(slug)||slug,slug));
  categoryFilter.value=contextCategory;const productSearch=filterBar.querySelector('input');productSearch.oninput=render;
  categoryFilter.onchange=()=>{contextCategory=categoryFilter.value;const url=new URL(location.href);if(contextCategory)url.searchParams.set('category',contextCategory);else url.searchParams.delete('category');history.replaceState(null,'',url);render()};
  function visibleProducts(){const query=productSearch.value.trim().toLocaleLowerCase();const visible=products.filter(p=>(!categoryFilter.value||(p.categories||[p.category]).includes(categoryFilter.value))&&(!query||[p.nameHe,p.nameEn,p.sku].some(value=>String(value||'').toLocaleLowerCase().includes(query))));return visible;}
  function render(){const visible=visibleProducts();filterBar.querySelector('span').textContent=visible.length+' מוצרים';list.innerHTML=visible.map(p=>`<div class="admin-row" data-order-id="${p.id}"><img src="${p.images[0]||''}" alt=""><div><strong>${p.nameHe}</strong><br><small>${p.sku}</small></div><div>${p.price} ש״ח</div><div>${[...(p.colors||[]),...(p.sizes||[]),...(p.styles||[])].join(', ')||'ללא בחירה'}</div><div>${p.active?'מוצג':'מוסתר'}</div><div class="actions"><button type="button" class="button secondary drag-product" aria-label="גרירת מוצר לסידור" title="גרירה לסידור">⠿</button><button type="button" class="button secondary" data-first="${p.id}">לראש הרשימה</button><button class="button secondary move-product" data-up="${p.id}" aria-label="הזזה למעלה">↑</button><button class="button secondary move-product" data-down="${p.id}" aria-label="הזזה למטה">↓</button><button class="button secondary" data-edit="${p.id}">עריכה</button><button class="button danger" data-delete="${p.id}">מחיקה</button></div></div>`).join('')||'<p class="empty">אין מוצרים בקטגוריה זו</p>'}
  const retryOrder=document.createElement('button');retryOrder.type='button';retryOrder.className='button secondary';retryOrder.textContent='ניסיון שמירה נוסף';retryOrder.hidden=true;filterBar.append(retryOrder);
  const orderSaver=createOrderSaver(products,async changes=>{const results=await Promise.allSettled(changes.map(({id,sortOrder})=>api.request('/rest/v1/electroshop_products?id=eq.'+id,{method:'PATCH',body:{sort_order:sortOrder},token:session.accessToken})));const failure=results.find(r=>r.status==='rejected');if(failure)throw failure.reason;},state=>{retryOrder.hidden=state!=='error';status(state==='saved'?'סדר המוצרים נשמר':state==='error'?'הסדר מוצג אך השמירה נכשלה. לחצו על ניסיון שמירה נוסף.':'שומר את הסדר ברקע...',state==='error'?'error':'ok');});
  list.addEventListener('click',event=>{const first=event.target.closest('[data-first]');if(!first)return;const scope=products.filter(p=>!categoryFilter.value||(p.categories||[p.category]).includes(categoryFilter.value));if(placeVisibleProduct(products,scope,first.dataset.first,scope[0]?.id)){render();orderSaver.schedule(products);status('המוצר הועבר לראש הרשימה. שומר...')}});
  let drag=null,dragFrame=0;
  function dragTick(){if(!drag)return;const edge=75,speed=drag.y<edge?-16:drag.y>innerHeight-edge?16:0;if(speed)window.scrollBy(0,speed);list.querySelectorAll('.drop-before,.drop-after').forEach(row=>row.classList.remove('drop-before','drop-after'));const row=document.elementFromPoint(drag.x,Math.max(0,Math.min(innerHeight-1,drag.y)))?.closest('[data-order-id]');drag.target=null;if(row&&list.contains(row)&&row.dataset.orderId!==drag.id){const rect=row.getBoundingClientRect();drag.target=row.dataset.orderId;drag.after=drag.y>rect.top+rect.height/2;row.classList.add(drag.after?'drop-after':'drop-before')}dragFrame=requestAnimationFrame(dragTick)}
  function finishDrag(commit){if(!drag)return;const saved=drag;drag=null;cancelAnimationFrame(dragFrame);document.body.classList.remove('product-dragging');list.querySelectorAll('.dragging,.drop-before,.drop-after').forEach(row=>row.classList.remove('dragging','drop-before','drop-after'));if(commit&&saved.target&&placeVisibleProduct(products,visibleProducts(),saved.id,saved.target,saved.after)){render();orderSaver.schedule(products)}}
  list.addEventListener('pointerdown',event=>{const handle=event.target.closest('.drag-product');if(!handle||event.button!==0)return;event.preventDefault();drag={id:handle.closest('[data-order-id]').dataset.orderId,x:event.clientX,y:event.clientY};handle.setPointerCapture(event.pointerId);handle.closest('[data-order-id]').classList.add('dragging');document.body.classList.add('product-dragging');dragTick()});
  list.addEventListener('pointermove',event=>{if(drag){drag.x=event.clientX;drag.y=event.clientY}});
  list.addEventListener('pointerup',()=>finishDrag(true));list.addEventListener('pointercancel',()=>finishDrag(false));
  window.addEventListener('keydown',event=>{if(event.key==='Escape')finishDrag(false)});

  retryOrder.onclick=()=>orderSaver.flush().catch(()=>{});
  window.addEventListener('beforeunload',event=>{if(orderSaver.pending()){event.preventDefault();event.returnValue='';}});
  const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const imageColorSelect=index=>{const groups=[['צבע',values(form.elements.colors.value).map(value=>({key:value,value}))],['מידה',values(form.elements.sizes.value).map(value=>({key:'@size:'+value,value}))],[form.elements.optionLabelHe.value||'אפשרות',values(form.elements.styles.value).map(value=>({key:'@style:'+value,value}))]];return `<select data-image-color="${index}" aria-label="שיוך תמונה לאפשרות"><option value="">ללא שיוך</option>${groups.filter(([,items])=>items.length).map(([label,items])=>`<optgroup label="${escapeHtml(label)}">${items.map(({key,value})=>`<option value="${escapeHtml(key)}" ${imageColors[index]===key?'selected':''}>${escapeHtml(value)}</option>`).join('')}</optgroup>`).join('')}</select>`};
  function renderImages(){primaryPreview.innerHTML=primaryImage?`<div class="preview-image primary"><img src="${primaryImage}" alt="תמונה ראשית"><button type="button" data-remove-primary aria-label="הסרת תמונה">×</button><strong>ראשית</strong>${imageColorSelect(0)}</div>`:'';additionalPreview.innerHTML=additionalImages.map((src,i)=>`<div class="preview-image"><img src="${src}" alt="תמונה נוספת ${i+1}"><button type="button" data-remove-additional="${i}" aria-label="הסרת תמונה">×</button>${imageColorSelect(i+1)}</div>`).join('');videoPreview.innerHTML=productVideos.map((src,i)=>`<div class="preview-video"><video src="${src}" controls preload="metadata"></video><button type="button" data-remove-video="${i}" aria-label="הסרת סרטון">×</button><strong>סרטון ${i+1}</strong></div>`).join('')}
  const variantKey=variant=>[variant.color||'',variant.size||'',variant.style||''].join('|');
  function createVariantCombinations(){const colors=values(form.elements.colors.value),sizes=values(form.elements.sizes.value),styles=values(form.elements.styles.value),axes=[colors.length?colors:[''],sizes.length?sizes:[''],styles.length?styles:['']],old=new Map(currentVariants.map(item=>[variantKey(item),item]));currentVariants=[];for(const color of axes[0])for(const size of axes[1])for(const style of axes[2]){if(!color&&!size&&!style)continue;const base={color,size,style},saved=old.get(variantKey(base));currentVariants.push({...base,price:saved?.price??''})}renderVariants()}
  function renderVariants(){variantsList.innerHTML=currentVariants.length?`<p class="variants-count">נוצרו ${currentVariants.length} שילובים</p>`+currentVariants.map((variant,index)=>`<div class="variant-row"><div class="variant-values">${variant.color?`<span><b>צבע:</b> ${escapeHtml(variant.color)}</span>`:''}${variant.size?`<span><b>מידה:</b> ${escapeHtml(variant.size)}</span>`:''}${variant.style?`<span><b>אפשרות:</b> ${escapeHtml(variant.style)}</span>`:''}</div><label>מחיר ש״ח<input type="number" min="0" step="0.01" data-variant-price="${index}" value="${escapeHtml(variant.price??'')}" placeholder="מחיר רגיל"></label></div>`).join(''):'<p class="variants-empty">הוסף צבעים, מידות או אפשרויות ולחץ „יצירת כל השילובים”.</p>'}
  function setRichValue(name,value=''){const wrapper=document.querySelector(`[data-rich-field="${name}"]`),editor=wrapper.querySelector('.rich-editor'),field=form.elements[name];const looksHtml=/<\/?[a-z][\s\S]*>/i.test(value);editor.innerHTML=looksHtml?value:escapeHtml(value).replace(/\n/g,'<br>');field.value=editor.innerHTML}
  function syncRichEditors(){document.querySelectorAll('[data-rich-field]').forEach(wrapper=>{form.elements[wrapper.dataset.richField].value=wrapper.querySelector('.rich-editor').innerHTML.trim()})}
  function nextSku(){const highest=products.reduce((max,product)=>{const match=String(product.sku||'').match(/^ELECTRO-(\d+)$/i);return match?Math.max(max,Number(match[1])):max},0);return `ELECTRO-${String(highest+1).padStart(3,'0')}`}
  const categoryChoices=document.createElement('fieldset');categoryChoices.className='field full product-category-choices';categoryChoices.innerHTML='<legend>קטגוריות המוצר</legend><small>אפשר לסמן כמה קטגוריות. אותו מוצר יוצג בכל הקטגוריות שסומנו.</small><div></div>';form.elements.category.closest('label').hidden=true;form.elements.category.closest('label').style.display='none';form.elements.category.required=false;form.elements.category.closest('label').after(categoryChoices);
  function selectCategories(product){const selected=product?(product.categories||[product.category]):[contextCategory];const container=categoryChoices.querySelector('div');container.replaceChildren();for(const slug of new Set([...categoryNames.keys(),...selected].filter(Boolean))){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.name='categories';input.value=slug;input.checked=selected.includes(slug);label.append(input,document.createTextNode(categoryNames.get(slug)||slug));container.append(label)}}
  function openForm(product){form.reset();formStatusEl.className='status form-status';formStatusEl.textContent='';primaryImage=product?.images?.[0]||'';additionalImages=product?.images?.slice(1)||[];imageColors=product?.imageColors?.slice()||Array(product?.images?.length||0).fill('');productVideos=product?.videos?.slice()||[];currentVariants=product?.variants?.map(item=>({...item}))||[];document.querySelector('#modalTitle').textContent=product?'עריכת מוצר':'הוספת מוצר';if(product){if(product.category&&!Array.from(form.elements.category.options).some(option=>option.value===product.category)){form.elements.category.add(new Option(product.category,product.category));}for(const [key,value] of Object.entries(product)){const field=form.elements[key];if(!field||['images','imageColors','videos','variants','descriptionHe','descriptionEn'].includes(key))continue;if(field.type==='checkbox')field.checked=!!value;else field.value=Array.isArray(value)?value.join('\n'):value}if(product.regularPrice<=product.price)form.elements.price.value=''}else{form.elements.id.value='';form.elements.sku.value=nextSku();form.elements.active.checked=true;const categoryField=form.elements.category;if(contextCategory&&!Array.from(categoryField.options).some(option=>option.value===contextCategory))categoryField.add(new Option(contextCategory,contextCategory));categoryField.value=contextCategory}selectCategories(product);setRichValue('descriptionHe',product?.descriptionHe||'');setRichValue('descriptionEn',product?.descriptionEn||'');renderImages();renderVariants();modal.classList.add('open')}
  const readFile=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});
  document.querySelector('#primaryImageFile').addEventListener('change',async e=>{const [file]=e.target.files;if(file){primaryImage=await readFile(file);imageColors[0]=''}renderImages();e.target.value=''});document.querySelector('#additionalImageFiles').addEventListener('change',async e=>{const files=[...e.target.files];if(files.length){additionalImages.push(...await Promise.all(files.map(readFile)));imageColors.push(...files.map(()=>''))}renderImages();e.target.value=''});document.querySelector('#productVideoFiles').addEventListener('change',async e=>{const [file]=e.target.files;if(file?.size>50*1024*1024){status('הסרטון חייב להיות קטן מ-50MB','error');e.target.value='';return}if(file)productVideos=[await readFile(file)];renderImages();e.target.value=''});const setImageColor=e=>{const select=e.target.closest('[data-image-color]');if(select)imageColors[Number(select.dataset.imageColor)]=select.value};primaryPreview.addEventListener('change',setImageColor);additionalPreview.addEventListener('change',setImageColor);form.elements.colors.addEventListener('change',renderImages);form.elements.optionLabelHe.addEventListener('change',renderImages);primaryPreview.addEventListener('click',e=>{if(e.target.closest('[data-remove-primary]')){primaryImage='';imageColors[0]='';renderImages()}});additionalPreview.addEventListener('click',e=>{const b=e.target.closest('[data-remove-additional]');if(!b)return;const index=Number(b.dataset.removeAdditional);additionalImages.splice(index,1);imageColors.splice(index+1,1);renderImages()});videoPreview.addEventListener('click',e=>{const b=e.target.closest('[data-remove-video]');if(!b)return;productVideos.splice(Number(b.dataset.removeVideo),1);renderImages()});
  document.querySelector('#generateVariants').onclick=createVariantCombinations;variantsList.addEventListener('input',e=>{const input=e.target.closest('[data-variant-price]');if(input)currentVariants[Number(input.dataset.variantPrice)].price=input.value});
  document.querySelectorAll('.rich-toolbar').forEach(toolbar=>toolbar.addEventListener('click',e=>{const button=e.target.closest('[data-command]');if(!button)return;const editor=toolbar.parentElement.querySelector('.rich-editor'),command=button.dataset.command;editor.focus();if(command==='createLink'){const url=prompt('כתובת הקישור');if(url)document.execCommand(command,false,url)}else document.execCommand(command,false,null)}));
  document.querySelector('#add').onclick=()=>window.open(editorUrl(),'_blank');document.querySelector('#cancel').onclick=()=>{if(editorMode){window.close();if(!window.closed)location.href='shop-admin.html'}else modal.classList.remove('open')};list.addEventListener('click',async e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]'),up=e.target.closest('[data-up]'),down=e.target.closest('[data-down]');if(up||down){const id=(up||down).dataset[up?'up':'down'];if(moveVisibleProduct(products,visibleProducts(),id,up?-1:1)){render();list.querySelector('[data-'+(up?'up':'down')+'="'+id+'"]').focus({preventScroll:true});orderSaver.schedule(products);} return}if(edit)window.open(editorUrl(edit.dataset.edit),'_blank');if(del&&confirm('למחוק את המוצר?')){try{await api.deleteProductRemote(session,del.dataset.delete);await orderSaver.flush();products=await api.getProducts(session);render();status('המוצר נמחק')}catch(error){status(error.message,'error')}}});const values=value=>String(value||'').split(/[,\n]/).map(x=>x.trim()).filter(Boolean);
  ['colors','sizes','styles'].forEach(name=>form.elements[name].addEventListener('change',()=>{createVariantCombinations();renderImages()}));
  importDescriptions.onclick=async()=>{importDescriptions.disabled=true;status('מייבא את תיאורי המוצרים...');try{const source=await fetch('_mehadrin-reference.html').then(response=>response.text()),descriptions=new Map();for(const match of source.matchAll(/product(\d+):\s*\{[\s\S]*?desc:\s*`([\s\S]*?)`\s*\}/g)){const sku=`ELECTRO-${match[1].padStart(3,'0')}`,description=match[2].replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]+>/g,'').replace(/\n{3,}/g,'\n\n').trim();descriptions.set(sku,description)}let updated=0;for(const product of products){const description=descriptions.get(product.sku);if(description){await api.updateProductDescription(session,product.id,description);updated++}}await orderSaver.flush();products=await api.getProducts(session);render();status(`${updated} תיאורים נשמרו ב-Supabase`)}catch(error){status(error.message,'error')}finally{importDescriptions.disabled=false}};
  form.addEventListener('submit',async event=>{
    event.preventDefault();
    syncRichEditors();
    const saveButton=form.querySelector('button:not([type="button"])');
    const data=new FormData(form);
    const selectedCategories=data.getAll('categories');if(!selectedCategories.length){status('יש לבחור לפחות קטגוריה אחת','error');return}const primaryCategory=selectedCategories.includes(data.get('category'))?data.get('category'):selectedCategories[0];
    const id=data.get('id')||`product-${crypto.randomUUID()}`;
    if(!primaryImage){status('יש לבחור תמונה ראשית','error');return}
    const regularPrice=Number(data.get('regularPrice'));
    const salePrice=data.get('price')?Number(data.get('price')):null;
    const product={
      id,sku:data.get('sku').trim(),nameHe:data.get('nameHe').trim(),nameEn:data.get('nameEn').trim(),
      descriptionHe:data.get('descriptionHe').trim(),descriptionEn:data.get('descriptionEn').trim(),
      featured:data.get('featured')==='on',pickupOnly:data.get('pickupOnly')==='on',category:primaryCategory,categories:selectedCategories,regularPrice,price:salePrice??regularPrice,
      priceUsd:data.get('priceUsd')?Number(data.get('priceUsd')):null,active:data.get('active')==='on',
      optionLabelHe:String(data.get('optionLabelHe')||'').trim(),optionLabelEn:String(data.get('optionLabelEn')||'').trim(),colors:values(data.get('colors')),sizes:values(data.get('sizes')),styles:values(data.get('styles')),
      variants:currentVariants.map(item=>({...item,price:item.price===''?null:Number(item.price)})),
      images:[primaryImage,...additionalImages],imageColors:[...imageColors],videos:productVideos
    };
    saveButton.disabled=true;saveButton.textContent='שומר...';
    try{status('שומר את המוצר...');await api.saveProductRemote(session,product);form.reset();status('המוצר נשמר ב-Supabase');if(editorMode){localStorage.setItem('electroshop_products_updated',crypto.randomUUID());setTimeout(()=>{window.close();if(!window.closed)location.href='shop-admin.html'},650)}else{modal.classList.remove('open');products=await api.getProducts(session);render()}}
    catch(error){const message=/duplicate key|products_sku_key/i.test(error.message||'')?'לא ניתן לשמור: המק״ט הזה כבר קיים. יש לבחור מק״ט אחר.':error.message;status(message,'error')}
    finally{saveButton.disabled=false;saveButton.textContent='שמירה'}
  });
  window.addEventListener('message',async event=>{if(event.origin!==location.origin||event.data?.type!=='electroshop-product-saved')return;await orderSaver.flush();products=await api.getProducts(session);render();status('רשימת המוצרים עודכנה')});

  window.addEventListener('storage',async event=>{if(event.key==='electroshop_products_updated'&&!editorMode){try{await orderSaver.flush();products=await api.getProducts(session);render();status('רשימת המוצרים עודכנה')}catch(error){status(error.message,'error')}}});
  document.addEventListener('electroshop-devices-updated',async()=>{await orderSaver.flush();products=await api.getProducts(session);if(!Array.from(categoryFilter.options).some(o=>o.value==='smartphones'))categoryFilter.add(new Option('מכשירים','smartphones'));render()});
  render();if(editorMode){const adminActions=document.querySelector('#add')?.closest('.head-actions');if(adminActions)adminActions.hidden=true;document.querySelector('.admin-shell').hidden=true;const product=editorId?products.find(item=>item.id===editorId):null;if(editorId&&!product){modal.classList.add('open');status('המוצר לא נמצא','error')}else openForm(product)}
}).catch(error=>{const message=document.querySelector('#status')||document.querySelector('#formStatus');if(message){message.textContent=error.message;message.className='status show error'}});